apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "esports-platform.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "esports-platform.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  AWS_REGION: {{ .Values.aws.region | quote }}
