apiVersion: v1
kind: Service
metadata:
  name: {{ include "esports-platform.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "esports-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "esports-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
