apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "esports-platform.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "esports-platform.labels" . | nindent 4 }}
  annotations:
    # IRSA: bind this ServiceAccount to the IAM role.
    # The EKS OIDC provider validates the ServiceAccount token and allows
    # the pod to assume this role without any long-lived AWS credentials.
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.aws.accountId }}:role/{{ .Values.aws.irsaRoleName }}"
automountServiceAccountToken: true
